In [1]:
import numpy as np
from sklearn.externals import joblib

In [2]:
model = joblib.load('dragon_real_estate.joblib')

#### First Input

In [6]:
our_input = np.array([[
    0.00632, 18, 2.31, 0, 0.538, 6.575, 65.2, 4.09, 1, 296, 15.3, 396.9, 4.98
]])

model.predict(our_input)

array([25.06])

#### Second Input

In [7]:
our_input = np.array([[
    0.06905, 0, 2.18, 0, 0.458, 7.147, 54.2, 6.0622, 3, 222, 18.7, 396.9, 5.33
]])
model.predict(our_input)

array([25.06])

#### Third Input

In [15]:
our_input = np.array([[-0.32145513, -0.4898311 , -0.46656149, -0.27288841, -0.17188021,
        0.55217183,  0.64698949,  0.23505856, -0.65766683, -0.62530717,
        1.18815263,  0.27969885, -0.11230576]])
model.predict(our_input)

array([21.39])